FROM node as build-deps
WORKDIR /app
COPY package*.json ./
RUN npm install && npm run build

FROM nginx
COPY --from=build-deps /usr/src/app/build /usr/share/nginx/html
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]